main.plugins.logcleaner.enabled = true
main.plugins.logcleaner.log_dir = "/etc/pwnagotchi/log/"
main.plugins.logcleaner.max_log_age_days = 7
main.plugins.logcleaner.max_log_size_mb = 10
main.plugins.logcleaner.pos_x = -10
main.plugins.logcleaner.pos_y = 0
main.plugins.logcleaner.interval = 1800
