main.plugins.logcleaner.enabled = true
main.plugins.logcleaner.log_dir = "/etc/pwnagotchi/log/"	# Customizable path
main.plugins.logcleaner.max_log_age_days = 7				# Delete logs older than X days
main.plugins.logcleaner.max_log_size_mb = 10				# Max storage in MB
main.plugins.logcleaner.pos_x = 150							
main.plugins.logcleaner.pos_y = 30							
main.plugins.logcleaner.text_color = "black"				# or "white"
main.plugins.logcleaner.interval = 3600						# Cleanup interval (seconds)
main.plugins.logcleaner.log_level = "DEBUG"					# DEBUG, INFO (default), WARNING, ERROR
